export const PRODUCT_MAKE_REQ = "PRODUCT_MAKE_REQ"; // Acción para iniciar una solicitud
export const PRODUCT_GETALL_SUCCESS = "PRODUCT_GETALL_SUCCESS"; // Acción para el éxito al obtener todas las solicitudes
export const PRODUCT_GETALL_FAIL = "PRODUCT_GETALL_FAIL"; // Acción para el fallo al obtener todas las solicitudes
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS"; // Acción para el éxito al obtener todas las solicitudes
export const PRODUCT_GETALL_FILTER_SUCCESS = "PRODUCT_GETALL_FILTER_SUCCESS"; // Acción para el éxito al obtener todas las solicitudes
export const PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL"; // Acción para el fallo al obtener todas las solicitudes
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS"; // Acción para el éxito al obtener todas las solicitudes
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS"; // Acción para el éxito al obtener todas las solicitudes
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL"; // Acción para el éxito al obtener todas las solicitudes
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL"; // Acción para el fallo al obtener todas las solicitudes
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"; // Acción para el éxito al obtener todas las solicitudes
